---
- hosts: all
  become: yes
  name: Drupal on LAMP setup
  vars_files:
    - vars/mysql_user_creds.yml
    - vars/drupal_admin_creds.yml
  vars:
    - drupal_site_basename: "Ansible'd Drupal site"
    - apache_root_dir: /var/www/html
    - drupal_dir: "{{ apache_root_dir }}/drupal"
    - drupal_site_name: |-
        {{ drupal_site_basename }} [{{ ansible_hostname }} (on {{ ansible_os_family }})]
  pre_tasks:
    - name: No nano
      package:
        name: nano
        state: absent
  roles:
    - lamp_packages
    - drupal_install
    - mysql_setup
  tasks:
    - debug: var=drupal_site_name
    - name: Set up default Drupal site if non-existing
      script:
        cmd: drupal_setup.sh
        creates: "{{ drupal_dir }}/sites/default/files"
      environment:
        SITE_NAME: "{{ drupal_site_name }}"
        DRUPAL_USER: "{{ drupal_user }}"
        DRUPAL_PASS: "{{ drupal_pass }}"
        MYSQL_USER: "{{ drupal_mysql_user }}"
        MYSQL_PASS: "{{ drupal_mysql_pass }}"
