- name: LAMP stack packages installed (apt)
  apt:
    name:
      - apache2
      - libapache2-mod-php
      - php-xml
      - php-gd
      - php-mbstring
      - php-mysql
      - mysql-server
    state: present
  notify: 'lamp_packages : restart_apache'
