---
- include_vars: "{{ansible_os_family}}.yml"
- include_tasks: update-{{ansible_os_family}}.yml
- include_tasks: LAMP-{{ansible_os_family}}.yml
- name: Apache & mysql services enabled & running
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ apache_service }}"
    - "{{ mysql_service }}"
